// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: proto/user/user.proto

package userpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserInternal_AreFriends_FullMethodName = "/user.UserInternal/AreFriends"
	UserInternal_GetUser_FullMethodName    = "/user.UserInternal/GetUser"
	UserInternal_BulkUsers_FullMethodName  = "/user.UserInternal/BulkUsers"
)

// UserInternalClient is the client API for UserInternal service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserInternalClient interface {
	AreFriends(ctx context.Context, in *AreFriendsRequest, opts ...grpc.CallOption) (*AreFriendsResponse, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	BulkUsers(ctx context.Context, in *BulkUsersRequest, opts ...grpc.CallOption) (*BulkUsersResponse, error)
}

type userInternalClient struct {
	cc grpc.ClientConnInterface
}

func NewUserInternalClient(cc grpc.ClientConnInterface) UserInternalClient {
	return &userInternalClient{cc}
}

func (c *userInternalClient) AreFriends(ctx context.Context, in *AreFriendsRequest, opts ...grpc.CallOption) (*AreFriendsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AreFriendsResponse)
	err := c.cc.Invoke(ctx, UserInternal_AreFriends_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userInternalClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, UserInternal_GetUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userInternalClient) BulkUsers(ctx context.Context, in *BulkUsersRequest, opts ...grpc.CallOption) (*BulkUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BulkUsersResponse)
	err := c.cc.Invoke(ctx, UserInternal_BulkUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserInternalServer is the server API for UserInternal service.
// All implementations must embed UnimplementedUserInternalServer
// for forward compatibility.
type UserInternalServer interface {
	AreFriends(context.Context, *AreFriendsRequest) (*AreFriendsResponse, error)
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	BulkUsers(context.Context, *BulkUsersRequest) (*BulkUsersResponse, error)
	mustEmbedUnimplementedUserInternalServer()
}

// UnimplementedUserInternalServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserInternalServer struct{}

func (UnimplementedUserInternalServer) AreFriends(context.Context, *AreFriendsRequest) (*AreFriendsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AreFriends not implemented")
}
func (UnimplementedUserInternalServer) GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedUserInternalServer) BulkUsers(context.Context, *BulkUsersRequest) (*BulkUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BulkUsers not implemented")
}
func (UnimplementedUserInternalServer) mustEmbedUnimplementedUserInternalServer() {}
func (UnimplementedUserInternalServer) testEmbeddedByValue()                      {}

// UnsafeUserInternalServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserInternalServer will
// result in compilation errors.
type UnsafeUserInternalServer interface {
	mustEmbedUnimplementedUserInternalServer()
}

func RegisterUserInternalServer(s grpc.ServiceRegistrar, srv UserInternalServer) {
	// If the following call pancis, it indicates UnimplementedUserInternalServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserInternal_ServiceDesc, srv)
}

func _UserInternal_AreFriends_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AreFriendsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserInternalServer).AreFriends(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserInternal_AreFriends_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserInternalServer).AreFriends(ctx, req.(*AreFriendsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserInternal_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserInternalServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserInternal_GetUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserInternalServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserInternal_BulkUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BulkUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserInternalServer).BulkUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserInternal_BulkUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserInternalServer).BulkUsers(ctx, req.(*BulkUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserInternal_ServiceDesc is the grpc.ServiceDesc for UserInternal service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserInternal_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserInternal",
	HandlerType: (*UserInternalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AreFriends",
			Handler:    _UserInternal_AreFriends_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _UserInternal_GetUser_Handler,
		},
		{
			MethodName: "BulkUsers",
			Handler:    _UserInternal_BulkUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/user/user.proto",
}
